services:
  # A Docker web service
  - type: web
    name: CloudWeb
    runtime: docker
    repo: https://github.com/BadPioche/CloudWebSite # optional
    region: frankfurt # optional (defaults to oregon)
    branch: main # optional (defaults to master)

databases:
  - name: postgredatabase
    databaseName: private

envVarGroups:
  - name: conc-settings
    envVars:
      - key: DB_URL
        fromDatabase:
          name: private
          property: connectionString
