services:
  - type: web
    name: CloudWeb
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/BadPioche/CloudWebSite # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free
    envVars:
      - key: DB_URL
        fromDatabase:
          name: postgredatabase
          property: connectionString

databases:
  - name: postgredatabase
    databaseName: private
    region: frankfurt
    plan: free